image: gradle:4.6-jdk8-alpine

stages:
  - build
  - test
  - deploy

before_script:
  #  - echo `pwd` # debug
  #  - echo "$CI_BUILD_NAME, $CI_BUILD_REF_NAME $CI_BUILD_STAGE" # debug
  #- sudo rm -R ./group15
  - export GRADLE_USER_HOME=`pwd`/.gradle

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

#Gradle build
build:
  stage: build
  script:
    - chmod +x ./gradle
    - bash ./gradlew build -info
    #- gradle build -info
  artifacts:
    paths:
      - build/libs/*.jar

#For testing the build
test:
  stage: test
  script:
    - bash ./gradlew test -info


#For deploying in test server
deploy_stagging:
  stage: deploy
  image: ruby:2.3
  script:
    #- apt-get update -qy
    #- apt-get install -y ruby-dev
    #- gem install dpl
    - sudo -S dpl --provider=heroku --app=$HEROKU_APPNAME_TEST --api-key=$HEROKU_API_KEY
  environment:
    name: test
    url: $HEROKU_APP_HOST_TEST
  only:
    - develop

#For deploying in production
deploy_production:
  stage: deploy
  image: ruby:2.3
  script:
    - sudo -S dpl --provider=heroku --app=$HEROKU_APPNAME_PRODUCTION --api-key=$HEROKU_API_KEY
  environment:
    name: production
    url: $HEROKU_APP_HOST_PRODUCTION
  only:
    - master
